backend:
  name: github
  repo: criscass/the-cassettas-blog
  branch: main
  site_domain: www.cassettas-reboot.xyz

# For local development
# local_backend: true

# Global defaults (non-templated)
media_folder: "src/assets/images"
public_folder: "../../../../assets/images"

# Enable editorial workflow for review process
publish_mode: editorial_workflow

collections:
  - name: "blog-it"
    label: "Blog Posts (Italian)"
    folder: "src/content/blog/it"
    create: true
    slug: "post-{{fields.post_number}}"
    path: "{{slug}}/index"
    extension: "md"
    format: "frontmatter"
    # Per-post upload folder in shared assets
    media_folder: "/src/assets/images/post-{{fields.post_number}}"
    public_folder: "../../../../assets/images/post-{{fields.post_number}}"
    fields:
      - label: "Post Number"
        name: "post_number"
        widget: "string"
        pattern: ['^[0-9]{5}$', 'Must be exactly 5 digits (e.g., 00042)']
        hint: "Enter 5-digit post number (e.g., 00042)"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Language", name: "language", widget: "hidden", default: "it"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "blog-en"
    label: "Blog Posts (English)"
    folder: "src/content/blog/en"
    create: true
    slug: "post-{{fields.post_number}}"
    path: "{{slug}}/index"
    extension: "md"
    format: "frontmatter"
    # Per-post upload folder in shared assets
    media_folder: "src/assets/images/post-{{fields.post_number}}"
    public_folder: "../../../../assets/images/post-{{fields.post_number}}"
    fields:
      - label: "Post Number"
        name: "post_number"
        widget: "string"
        pattern: ['^[0-9]{5}$', 'Must be exactly 5 digits (e.g., 00042)']
        hint: "Enter 5-digit post number (e.g., 00042)"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Content", name: "body", widget: "markdown"}